In [1]:
import numpy as np
from numpy import linalg

In [2]:
x = np.random.random(size=(2, 3))
y = np.random.random(size=(2, 3))

In [3]:
np.dot(x, y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [4]:
x

array([[0.53418261, 0.36470888, 0.3291587 ],
       [0.83327749, 0.98893991, 0.91915549]])

In [5]:
y

array([[0.1718213 , 0.2443435 , 0.33817144],
       [0.66172083, 0.44871412, 0.75972261]])

In [9]:
np.transpose(np.diag(np.dot(x, np.transpose(y))))

array([0.29221027, 1.69345158])

In [8]:
np.dot(x[0, :], np.transpose(y[0, :]))

0.2922102681015146

In [12]:
np.linalg.norm(x, axis=0)

array([0.98979919, 1.05404683, 0.97631566])